In [20]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to tensor

### Creating Tensors

In [21]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [22]:
scalar.ndim

0

In [23]:
# Get tensor back as Python int
scalar.item()

7

In [24]:
# Vector
vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [25]:
vector.ndim

1

In [26]:
vector.shape

torch.Size([2])

In [27]:
# Matrix
matrix=torch.tensor([[7, 8],
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [28]:
matrix.ndim

2

In [29]:
matrix.shape

torch.Size([2, 2])

In [30]:
# Tensor
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [1,5,6]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [1, 5, 6]]])

In [31]:
tensor.ndim

3

In [32]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors

In [33]:
# Creating Random Tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5413, 0.5978, 0.6784, 0.0339],
        [0.9665, 0.8984, 0.2229, 0.3674],
        [0.2341, 0.0358, 0.4022, 0.3632]])

In [34]:
random_tensor.ndim

2

In [35]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and One

In [36]:
# Create a tensor with all zeros
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
# Create a tensors of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones*(random_tensor/random_tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
ones.dtype

torch.float32