In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to tensor

### Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector= torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
matrix=torch.tensor([[7, 8],
                      [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
# Tensor
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [1,5,6]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [1, 5, 6]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

### Random Tensors

In [14]:
# Creating Random Tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.7183, 0.4123, 0.3615, 0.0286],
        [0.0876, 0.1895, 0.1056, 0.1308],
        [0.7413, 0.9090, 0.4129, 0.4030]])

In [15]:
random_tensor.ndim

2

In [16]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

### Zeros and One

In [17]:
# Create a tensor with all zeros
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensors of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones*(random_tensor/random_tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Creating a range of tensor and tensors like

In [22]:
# Using torch.range()
torch.range(0,10)

/tmp/ipython-input-22-1952565514.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [23]:
one_to_ten=torch.arange(start=1,end=1000,step=100)
one_to_ten

tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

In [24]:
# Creating Tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors datatypes

In [25]:
# Float 32 tensor
float_32= torch.tensor([3.0,6.0,9.0],
                       dtype=None,
                       device=None,
                       requires_grad=False)
float_32

tensor([3., 6., 9.])

In [26]:
float_32.dtype

torch.float32

In [27]:
float_16=float_32.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
float_16*float_32

tensor([ 9., 36., 81.])

### Getting information from tensors

In [29]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0893, 0.6349, 0.8837, 0.6015],
        [0.5335, 0.3557, 0.2369, 0.0074],
        [0.0233, 0.2002, 0.5193, 0.1775]])

### Manipulating Tensors

In [30]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [31]:
tensor*10

tensor([10, 20, 30])

In [32]:
tensor-10

tensor([-9, -8, -7])

### Matrix Multiplication

In [33]:
# element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.1566, 0.1346, 0.9387],
        [0.1619, 0.2675, 0.9876],
        [0.1242, 0.3606, 0.7782]])

Shape Errors

In [36]:
# Shapes for matrix multiplication
tensor_1= torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_2=torch.tensor([[7,8],
                       [9,10]])
torch.matmul(tensor_1, tensor_2)

tensor([[ 25,  28],
        [ 57,  64],
        [ 89, 100]])

## Finding the min,max,mean,sum,etc(tensor aggregation)

In [37]:
# Create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
# find the min
torch.min(x)

tensor(0)

In [39]:
torch.max(x)

tensor(90)

In [40]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [41]:
torch.max(x)

tensor(90)

### Finding the positional min and max

In [42]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
# Finding the positional min
x.argmin()

tensor(0)

In [44]:
# Finding the positional max
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, unsqueezing tensors

In [45]:
# Create a tensor
x= torch.arange(1., 10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [46]:
# Add an extra dimension
x_reshaped= x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# Change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
# Changing z changes x
z[:,0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [49]:
# Stacking tensors on top of each other
x_stacked= torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [50]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [51]:
x_squeezed=x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [52]:
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [53]:
x_unsqueezed.shape

torch.Size([1, 9])

In [54]:
# Permute
x_original=torch.rand(size=(224,224,3))
x_permuted= x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing

In [55]:
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [56]:
# Index on our new Tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [57]:
# Index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [58]:
# Index on the inner bracket
x[0][0][0]

tensor(1)

In [59]:
x[:,1,1]

tensor([5])

## PyTorch Tensors And NumPy

In [60]:
# Numpy array to tensor
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [61]:
# tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [62]:
numpy_tensor.dtype

dtype('float32')

## Reproducbility

In [63]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.6628, 0.2703, 0.4766, 0.3359],
        [0.9985, 0.3139, 0.0274, 0.3569],
        [0.9588, 0.9053, 0.8109, 0.9777]])
tensor([[0.6703, 0.8860, 0.7536, 0.2329],
        [0.1773, 0.8254, 0.2549, 0.1713],
        [0.7145, 0.1422, 0.4596, 0.2502]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [64]:
random_seed=42
torch.manual_seed(random_seed)
random_tensor_C=torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
